#!/bin/bash
cd $(dirname $0)
set -o verbose
java -cp "commons-cli-1.0.jar:mysql-connector-java-5.1.12-bin.jar:commons-logging.jar:commons-beanutils.jar:commons-codec.jar:commons-collections.jar:commons-dbcp.jar:commons-digester.jar:commons-discovery.jar:commons-fileupload.jar:commons-httpclient.jar:commons-io.jar:commons-lang.jar:commons-pool.jar:commons-validator.jar:spring-aop.jar:spring-beans.jar:spring-context-support.jar:spring-context.jar:spring-core.jar:spring-jdbc.jar:spring-jms.jar:spring-orm.jar:spring-test.jar:spring-tx.jar:spring-web.jar:spring-webmvc-portlet.jar:spring-webmvc-struts.jar:spring-webmvc.jar:spring.jar:PicturePress_20_BatchJob.jar:PicturePress_10_Common.jar" com.picturepress.client.ParsePostFromFile $@
