--
-- Dumping data for table `blog`
--

UPDATE `blog` SET `intro`= '<a href="http://blog.sina.com.cn/zhaotingjingmei" target="_new"><b>赵庭景美</b> “Zhao Ting Jing Mei”</a><br/>\r\n<br/>\r\n<b>location</b>: Beijing<br/>\r\n<b>occupation</b>: oil painter<br/>\r\n<b>blog visits</b>: 88, 086<br/>\r\n<br/>\r\nShe came home one night to find her husband in bed with another woman, and broadcast the whole thing live on her microblog.<br/>' WHERE `blog_id` = 1;
UPDATE `blog` SET `intro`= '<a href="http://t.sina.com.cn/n/钟如九" target="_new"><b>钟如九</b> “Zhong Rujiu”</a><br/>\r\n<br/>\r\n<b>age</b>: 22<br/>\r\n<b>location</b>: Yihuang county, Jiangxi<br/>\r\n<b>microblog readership</b>: 31,966<br/>\r\n<br/>\r\nChased by local police on her way to Beijing to petition against the forced demolition of her family’s home, she and her sister locked  themselves in the airport washroom and began texting bloggers and journalists for help. She writes updates from her mobile phone.<br/>' WHERE `blog_id` = 2;
UPDATE `blog` SET `intro`= '<a href="http://blog.sina.com.cn/honghuang" target="_new"><b>洪晃</b> “Hong Huang”</a><br/>\r\n<br/>\r\n<b>location</b>: Beijing<br/\r\n<b>occupation</b>: Chief executive of China Interactive Media Group<br/>\r\n<b>blog visits</b>: 113,369,616<br/>\r\n<br/>\r\nShe is an influential media mogul, publisher of fashion magazines, the ex-wife of a famous film director, a mother, and the daughter of diplomatic family. <br/>' WHERE `blog_id` = 3;
UPDATE `blog` SET `intro`= '<a href="http://452598814.qzone.qq.com/" target="_new"><b>流氓燕</b> “Hooligan Sparrow”</a><br/>\r\n<br/>\r\n<b>location</b>: Wuhan<br/>\r\n<b>occupation</b>: community organizer<br/>\r\n<b>blog visits</b>: 3,048,638<br/>\r\n<br/>\r\nShe first broke taboos by posting nude photos of herself online, and writing candidly about sex and relationships. She now runs a women''s rights organization, and is a community organizer campaigning for the legalization of sex work in China. <br/>' WHERE `blog_id` = 4;
UPDATE `blog` SET `intro`= '<a href="http://dimplewan.wordpress.com/" target="_new"><b>丁婆</b> “Dimple”</a><br/>\r\n<br/>\r\n<b>location</b>: Montreal, Canada\r\n<br/>\r\n<b>occupation</b>: student, office assistant<br/>\r\n<b>blog hits</b>: 13<br/>\r\n<br/>\r\nBlogging is an outlet for the ups and downs in her daily life. Some things are easier to say online, to total strangers, than to tell her friends.<br/>' WHERE `blog_id` = 5;
